services:
  web: 
    build:
      context: app
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - $PWD/app:/app
