version: '3'

networks:
  internal:
  external:


services:
  flask:
    build:
      context: .
      target: builder
    stop_signal: SIGINT
    restart: always
    networks:
      - internal
      - external
    ports:
      - 8001:8001
    command: gunicorn -w 1 -b 0.0.0.0:8001 "wsgi:create_app('docker')"
    depends_on:
      - db

  db:
    image: postgres:15.2
    restart: always
    networks:
      - internal
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    networks:
      - internal
      - external
    ports:
      - 8080:8080

volumes:
  database: