version: '3'

networks:
  internal:
    name: database_internal
    external: True
  external:


services:
  flask:
    build:
      context: .
      target: builder
    stop_signal: SIGINT
    restart: always
    networks:
      - internal
      - external
    ports:
      - 8001:8001
    command: gunicorn -w 1 -b 0.0.0.0:8001 "wsgi:create_app('docker')"


