version: '3'

networks:
  my_cool_network:
    name: my_cool_network

services:
  web:
    build:
      context: .
      target: builder
    stop_signal: SIGINT
    restart: always
    networks:
      - my_cool_network
    ports:
      - 8001:8001
    command: gunicorn -w 1 -b 0.0.0.0:8001 "wsgi:create_app('docker')"
