name: Build, Push, and Deploy

on:
  push:
    branches:
      - main
      - test

jobs:

  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest

    - name: Set up doctl
      uses: digitalocean/action-doctl@v2
      with:
        version: latest
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Deploy Docker image
      run: |
        doctl compute ssh ${{ secrets.DROPLET_NAME }} --ssh-command "docker pull ghcr.io/${{ github.repository }}:latest"
